name: release
on: 
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn install

      # - name: Typecheck
      #   run: yarn test:ts

      # - name: Tests (Jest)
      #   run: yarn test:unit

      - name: Test (Cypress) with Replay
        run: yarn test:e2e:replay
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata
          RECORD_REPLAY_TEST_METRICS: 1
          # These two are here to help with measuring the true overhead by disabling diagnostics
          RECORD_REPLAY_DISABLE_ASSERTS: 1
          RECORD_REPLAY_DISABLE_SOURCEMAP_COLLECTION: 1

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.6
        with:
          api-key: rwk_S5uQMTExBpKEeShwGVUORIe3c1v1TzzUUduohvTZPYG

      # - name: Build
        # run: yarn build
